//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPolicyDetail
    {
        public Nullable<int> PolicyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RegisterdDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> PolicyAmount { get; set; }
        public string PolicyTerm { get; set; }
        public Nullable<int> UserNoTerms { get; set; }
        public Nullable<double> PremiumAmount { get; set; }
        public string NomineeName { get; set; }
        public string NomineeRelation { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public int RegisteredID { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
        public virtual UsersRegistrationDetail UsersRegistrationDetail { get; set; }
    }
}
