//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjuryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InjuryType()
        {
            this.PolicyClaims = new HashSet<PolicyClaim>();
        }
    
        public Nullable<int> PolicyID { get; set; }
        public string InjuryName { get; set; }
        public int InjuryID { get; set; }
        public string InjuryDescription { get; set; }
        public int ReimbursePercent { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyClaim> PolicyClaims { get; set; }
    }
}
