//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyDetail()
        {
            this.CustomerPolicyDetails = new HashSet<CustomerPolicyDetail>();
            this.InjuryTypes = new HashSet<InjuryType>();
            this.PolicyCoverages = new HashSet<PolicyCoverage>();
        }
    
        public int PolicyID { get; set; }
        public string PolicyName { get; set; }
        public Nullable<int> MaturityYears { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPolicyDetail> CustomerPolicyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryType> InjuryTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyCoverage> PolicyCoverages { get; set; }
        public virtual UsersRegistrationDetail UsersRegistrationDetail { get; set; }
    }
}
