//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyCoverage
    {
        public Nullable<int> PolicyID { get; set; }
        public Nullable<int> PolicyDuration { get; set; }
        public Nullable<double> PolicyAmount { get; set; }
        public Nullable<double> PolicyCoverageAmount { get; set; }
        public int Srlno { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
    }
}
