//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumPayment
    {
        public Nullable<int> RegistredID { get; set; }
        public Nullable<double> PayAmount { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public int ReceiptNumber { get; set; }
    
        public virtual UsersRegistrationDetail UsersRegistrationDetail { get; set; }
    }
}
